<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Andreas Varotsis">
<meta name="dcterms.date" content="2026-09-29">
<meta name="description" content="Draft working paper comparing sustained and temporary recorded-crime patterns around both CONNECT drops using six-force and national synthetic controls.">

<title>Two CONNECT drops and a recording break, version 2 – Andreas Varotsis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-37760b2b8fe23d2514863e33923e39df.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=GG-378MDZNVX4"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'GG-378MDZNVX4', { 'anonymize_ip': true});
</script>
<style>html{ scroll-behavior: smooth; }</style>
<meta name="quarto:status" content="draft">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Two CONNECT drops and a recording break, version 2 – Andreas Varotsis">
<meta property="og:description" content="Draft working paper comparing sustained and temporary recorded-crime patterns around both CONNECT drops using six-force and national synthetic controls.">
<meta property="og:image" content="https://andreasthinks.me/papers/connect-two-drops-v2/figures/figure-1.png">
<meta property="og:site_name" content="Andreas Varotsis">
<meta property="og:image:height" content="553">
<meta property="og:image:width" content="1209">
<meta name="twitter:title" content="Two CONNECT drops and a recording break, version 2 – Andreas Varotsis">
<meta name="twitter:description" content="Draft working paper comparing sustained and temporary recorded-crime patterns around both CONNECT drops using six-force and national synthetic controls.">
<meta name="twitter:image" content="https://andreasthinks.me/papers/connect-two-drops-v2/figures/figure-1.png">
<meta name="twitter:image-height" content="553">
<meta name="twitter:image-width" content="1209">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner"><div id="quarto-draft-alert" class="alert alert-warning"><i class="bi bi-pencil-square"></i>Draft</div>
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Andreas Varotsis</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">about</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../recent_work.html"> 
<span class="menu-text">talks &amp; publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../slides/index.html"> 
<span class="menu-text">teaching</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://fosstodon.org/@AndreasThinks" rel="me"> 
<span class="menu-text"><i class="fa-brands fa-mastodon fa-xl" aria-label="mastodon"></i></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bsky.app/profile/andreasthinks.me"> 
<span class="menu-text"><i class="fa-brands fa-bluesky fa-xl" aria-label="bluesky"></i></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://twitter.com/AndreasThinks"> 
<span class="menu-text"><i class="fa-brands fa-twitter fa-xl" aria-label="twitter"></i></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/AndreasThinks"> 
<span class="menu-text"><i class="fa-brands fa-github fa-xl" aria-label="github"></i></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.linkedin.com/in/avarotsis/"> 
<span class="menu-text"><i class="fa-brands fa-linkedin fa-xl" aria-label="linkedin"></i></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="mailto:andreas.varotsis@gmail.com"> 
<span class="menu-text"><i class="fa-solid fa-envelope fa-xl" aria-label="envelope"></i></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.xml"> 
<span class="menu-text"><i class="fa-solid fa-rss fa-xl" aria-label="rss"></i></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Two CONNECT drops and a recording break, version 2</h1>
            <p class="subtitle lead">Recorded-crime departures in the Metropolitan Police against a six-force and a nationally screened comparison</p>
                  <div>
        <div class="description">
          Draft working paper comparing sustained and temporary recorded-crime patterns around both CONNECT drops using six-force and national synthetic controls.
        </div>
      </div>
                </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Andreas Varotsis </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">September 29, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#lay-summary" id="toc-lay-summary" class="nav-link active" data-scroll-target="#lay-summary">Lay summary</a></li>
  <li><a href="#abstract" id="toc-abstract" class="nav-link" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#question-and-what-version-2-changes" id="toc-question-and-what-version-2-changes" class="nav-link" data-scroll-target="#question-and-what-version-2-changes">1. Question and what version 2 changes</a></li>
  <li><a href="#institutional-timeline-and-the-joint-second-break" id="toc-institutional-timeline-and-the-joint-second-break" class="nav-link" data-scroll-target="#institutional-timeline-and-the-joint-second-break">2. Institutional timeline and the joint second break</a></li>
  <li><a href="#data-outcomes-and-estimands" id="toc-data-outcomes-and-estimands" class="nav-link" data-scroll-target="#data-outcomes-and-estimands">3. Data, outcomes and estimands</a></li>
  <li><a href="#two-comparison-pools" id="toc-two-comparison-pools" class="nav-link" data-scroll-target="#two-comparison-pools">4. Two comparison pools</a></li>
  <li><a href="#held-out-prediction-before-drop-1" id="toc-held-out-prediction-before-drop-1" class="nav-link" data-scroll-target="#held-out-prediction-before-drop-1">5. Held-out prediction before Drop 1</a></li>
  <li><a href="#sustained-departures-after-march-2024" id="toc-sustained-departures-after-march-2024" class="nav-link" data-scroll-target="#sustained-departures-after-march-2024">6. Sustained departures after March 2024</a></li>
  <li><a href="#temporary-departures-around-each-break" id="toc-temporary-departures-around-each-break" class="nav-link" data-scroll-target="#temporary-departures-around-each-break">7. Temporary departures around each break</a></li>
  <li><a href="#uncertainty-what-the-intervals-do-and-do-not-mean" id="toc-uncertainty-what-the-intervals-do-and-do-not-mean" class="nav-link" data-scroll-target="#uncertainty-what-the-intervals-do-and-do-not-mean">8. Uncertainty: what the intervals do and do not mean</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">9. Discussion</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">10. Limitations</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">11. Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  <li><a href="#appendix-a.-reproducibility" id="toc-appendix-a.-reproducibility" class="nav-link" data-scroll-target="#appendix-a.-reproducibility">Appendix A. Reproducibility</a></li>
  <li><a href="#appendix-b.-changes-from-version-1" id="toc-appendix-b.-changes-from-version-1" class="nav-link" data-scroll-target="#appendix-b.-changes-from-version-1">Appendix B. Changes from version 1</a></li>
  <li><a href="#appendix-c.-narrative-consistency-checks" id="toc-appendix-c.-narrative-consistency-checks" class="nav-link" data-scroll-target="#appendix-c.-narrative-consistency-checks">Appendix C. Narrative consistency checks</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Draft working paper
</div>
</div>
<div class="callout-body-container callout-body">
<p>Reading edition of the verified version 2 notebook. Not peer reviewed. The analysis and results are unchanged; code and reproducibility files are available in the <a href="https://github.com/AndreasThinks/impact-of-connect-drop/blob/f52b08ae3470f1986f663165d2f97fa3c605b596/papers/connect_two_drops/v2/paper_v2.ipynb">source notebook</a>.</p>
</div>
</div>
<p><strong>Working paper, version 2 (29 September 2026).</strong> Not peer reviewed, not submitted, and not a claim of causal identification. Version 1 is preserved unchanged as <a href="https://github.com/AndreasThinks/impact-of-connect-drop/blob/f52b08ae3470f1986f663165d2f97fa3c605b596/papers/connect_two_drops/paper.ipynb"><code>../paper.ipynb</code></a>; Appendix B lists what changed.</p>
<p><strong>AI assistance disclosure.</strong> Analysis code, the national donor-pool experiment, its review and this notebook were AI-assisted. The national experiment was implemented by Claude Opus and completed by Codex Astra. It was then independently reviewed by Claude Opus (<code>claude-opus-5-5</code>), whose findings are in <a href="https://github.com/AndreasThinks/impact-of-connect-drop/blob/f52b08ae3470f1986f663165d2f97fa3c605b596/papers/connect_two_drops/../connect_national_pool/FINAL_OPUS_REVIEW.md"><code>../../connect_national_pool/FINAL_OPUS_REVIEW.md</code></a>, and this version was drafted from the reviewed results. Every number in the text is computed from the frozen inputs in <code>data/</code> when the notebook runs. The author is responsible for the content.</p>
<pre class="text"><code>Inputs verified against MANIFEST.json; v1 estimator module unchanged.</code></pre>
<section id="lay-summary" class="level2">
<h2 class="anchored" data-anchor-id="lay-summary">Lay summary</h2>
<p>The Metropolitan Police Service (MPS) replaced several of its computer systems with a single system, CONNECT. The first stage (“Drop 1”) went live on 29 November 2022. A second stage (“Drop 2”) was planned for February 2024. On 28 February 2024 the MPS also switched its crime-recording system from CRIS to CONNECT. This paper asks whether recorded crime in London changed around these dates, compared with what other police forces suggest would have happened.</p>
<p><strong>How.</strong> We build a “synthetic London” for each crime type: a weighted blend of other forces that tracked London’s recorded crime before December 2022. We then measure how far London moved away from it afterwards. Version 1 used six comparison forces. Version 2 adds a second comparison built from all 30 forces in England and Wales that passed data-quality and IT-change screens, and reports both.</p>
<p><strong>What we found.</strong></p>
<ul>
<li><strong>The wider comparison is better at predicting London before CONNECT, but only in total.</strong> On the last pre-CONNECT year, its prediction error for total recorded crime is 3.2% of London’s monthly level, against 5.4% for six forces. It is worse for shoplifting and theft from the person.</li>
<li><strong>Shoplifting and theft from the person rose far more in London than either comparison predicts.</strong> After March 2024 London’s recorded shoplifting averaged about 79% above the national comparison’s projection, and theft from the person about 106% above it. No other force departs this far from its own synthetic comparison. The rise does not line up neatly with either CONNECT date.</li>
<li><strong>For total recorded crime, the answer depends on the comparison and is not unusual either way.</strong> Against six forces London is about 1.4% above projection after March 2024; against the national pool about 8.1%. But untreated forces analysed the same way also drift this much from their own comparisons: London ranks 10th of 31.</li>
<li><strong>Around the March 2024 switch, recorded “other crime” dipped briefly and other theft fell without a clear recovery.</strong> Version 1’s finding of a temporary fall in drugs offences is weaker with the wider comparison.</li>
</ul>
<p><strong>What this does not show.</strong> None of these results shows that CONNECT changed crime. London differs from other areas in many ways. Recorded crime depends on how crimes are reported, recorded and published, and the MPS changed its recording system at exactly the second date studied. The results describe recorded-crime patterns under a stated model; they are not causal effects.</p>
</section>
<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p><strong>Background.</strong> The MPS introduced CONNECT in stages. Drop 1 (Case, Custody and Property) went live on 29 November 2022. Drop 2 was scheduled for February 2024, but no public source located gives its go-live day. MPS FOI disclosures date the replacement of the CRIS crime-recording system by CONNECT to 28 February 2024. The second break is therefore a joint Drop 2 / recording-transition window.</p>
<p><strong>Design.</strong> Monthly police.uk recorded-crime counts, thirteen categories plus their total, February 2019 to April 2026 (46 months before Drop 1, 15 between the breaks, 26 after March 2024). For each series a standardised synthetic control is fitted on pre-Drop 1 months only, and the MPS-minus-synthetic gap is described by a two-break segmented regression and by event-time departures. Two comparison pools are reported side by side: - the six forces of version 1; - a pre-specified national pool of 30 England and Wales forces that pass territorial, interference, file-completeness, low-count and documented recording-system-change screens.</p>
<p>Held-out pre-Drop 1 prediction, placebo analyses of every comparison force, specification grids and donor-composition resampling assess each pool.</p>
<p><strong>Results.</strong> - <strong>Validation.</strong> The national pool lowers held-out aggregate prediction error in all three validation schemes; for the last pre-Drop 1 year, 3.2% against 5.4%. It does not improve shoplifting or theft from the person. - <strong>Persistent category patterns.</strong> Both pools find large positive post-March 2024 departures in shoplifting (+67.6% six-force, +79.4% national, as % of the MPS pre-Drop 1 mean) and theft from the person (+127.3%, +106.2%). Both rank first among all 31 national units and remain large in every specification, screening and donor-composition sensitivity examined. - <strong>Aggregate.</strong> The departure is +1.4% with six forces and +8.1% nationally (core robustness range 6.3 to 13.7%). The national figure ranks only 10th of 31: untreated forces show departures of similar scale. - <strong>Inference check.</strong> Nominal 95% HAC intervals exclude zero for 47% of untreated placebo force-series, so they are not used as evidence. - <strong>Temporary patterns.</strong> A short fall in “other crime” around the March 2024 transition remains, with a narrow margin. Version 1’s drugs pattern no longer meets the robustness rule.</p>
<p><strong>Interpretation.</strong> These are descriptive, model-conditional departures in recorded crime. They are not estimates of the causal effect of CONNECT.</p>
</section>
<section id="question-and-what-version-2-changes" class="level2">
<h2 class="anchored" data-anchor-id="question-and-what-version-2-changes">1. Question and what version 2 changes</h2>
<p>Version 1 compared the MPS with six forces inherited from the companion Drop 1 paper (Varotsis, 2024). Two of its conclusions depended on that choice:</p>
<ul>
<li>the aggregate post-2024 departure was close to zero, but changed sign when the dominant donor was removed;</li>
<li>its placebo comparisons had only seven units.</li>
</ul>
<p>Version 2 asks whether a broader, rule-based comparison pool gives better pre-Drop 1 prediction and more stable post-period findings, and restates every finding under both pools. The estimator, break dates, analysis window and temporary-effect definitions are unchanged from version 1; only the donor pool differs. A final independent review added:</p>
<ul>
<li>placebo calibration of the interval estimates;</li>
<li>solver certificates;</li>
<li>leakage checks.</li>
</ul>
<p>That review changed how uncertainty is reported (Section 7).</p>
</section>
<section id="institutional-timeline-and-the-joint-second-break" class="level2">
<h2 class="anchored" data-anchor-id="institutional-timeline-and-the-joint-second-break">2. Institutional timeline and the joint second break</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Event</th>
<th>Date in primary source</th>
<th>Coding in the monthly panel</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Drop 1 go-live (Case, Custody, Property)</td>
<td>29 November 2022</td>
<td>First full post month December 2022</td>
<td>MPS, <em>CONNECT Update</em>, 30 June 2023, para 3.4; MOPAC PCD 1507</td>
</tr>
<tr class="even">
<td>Drop 2 planning dates</td>
<td>May 2023, then November 2023, then February 2024</td>
<td>Not used</td>
<td>June 2023 CONNECT Update; MOPAC PCD 1507 (4 August 2023); MOPAC PCD1572 (21 December 2023)</td>
</tr>
<tr class="odd">
<td>Drop 2 scheduled go-live</td>
<td>February 2024 (exact day not located)</td>
<td>Part of the joint second-break window</td>
<td>MOPAC PCD1572, paras 1.3 and 2.1</td>
</tr>
<tr class="even">
<td>CRIS last used / CONNECT records crime</td>
<td>27 / 28 February 2024</td>
<td>First full post month March 2024</td>
<td>MPS FOI 01.FOI.25.042468; MPS FOI 01.FOI.24.036412</td>
</tr>
<tr class="odd">
<td>MPS crime data late to police.uk</td>
<td>Not provided on time for Feb, Mar, May, Jun and Jul 2024 (Feb and Mar refreshed April 2024)</td>
<td>Donut sensitivity excludes Feb to Jul 2024</td>
<td>data.police.uk changelog</td>
</tr>
<tr class="even">
<td>MPS classification alignment with Home Office groupings</td>
<td>October 2025 (MPS dashboard)</td>
<td>Truncation sensitivity ends September 2025</td>
<td>London Datastore, MPS Monthly Crime Dashboard notes</td>
</tr>
<tr class="odd">
<td>MPS criminal damage collapses in police.uk street files</td>
<td>May 2026 onward</td>
<td><strong>Analysis window ends April 2026</strong></td>
<td>Raw July 2026 archive; no changelog entry</td>
</tr>
</tbody>
</table>
<p><strong>Why the second break is “joint”.</strong> MOPAC documents give only a planned month for Drop 2, and that plan moved twice. The recording-system cutover is dated precisely to 28 February 2024. The second break is coded at March 2024, the first full month after the cutover. It therefore combines a programme release, a change of crime-recording system and a period of late data supply to police.uk. These cannot be separated with monthly data. The CRIS date is not treated as a verified Drop 2 date. Timing is shifted by one month in each direction in the robustness grid, and a donut excludes February to July 2024. Drop 1 was not a single clean shock either: the June 2023 update records continuing stability problems, and PCD1572 notes Drop 1 patches still being deployed in November and December 2023.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure-1.png" class="img-fluid figure-img"></p>
<figcaption>Analysis figure 1</figcaption>
</figure>
</div>
<p><strong>Figure 1.</strong> Recorded criminal damage and arson, indexed to the January to April 2026 mean. MPS records fall from 4,330 in April 2026 to 221 in May 2026, while the national comparison pool total does not change. No data.police.uk changelog entry explains the MPS fall (changelog re-checked 29 September 2026). May to July 2026 are therefore excluded from the main analysis and used only in sensitivities. The national total stops in June 2026 because one pool force has no July file.</p>
</section>
<section id="data-outcomes-and-estimands" class="level2">
<h2 class="anchored" data-anchor-id="data-outcomes-and-estimands">3. Data, outcomes and estimands</h2>
<p><strong>Data.</strong> Street-level crime files from the data.police.uk archive, aggregated to force by category by month. The vintage plan is the same as version 1:</p>
<ul>
<li>February 2019 to July 2020 come from the December 2020 archive;</li>
<li>August 2020 to July 2023 from the July 2023 archive;</li>
<li>August 2023 onward from the July 2026 archive.</li>
</ul>
<p>A crime is a row with a non-blank Crime ID; anti-social behaviour is excluded. A force-month with no street file is missing, never zero. A category absent from a present file counts as zero <em>supplied</em> records. The v2 notebook reads only the compact extracts in <code>data/</code>: a count panel for the MPS and the 31 comparison forces used by either pool, plus saved results of the executed experiment. It never reads raw ZIPs or Git LFS files.</p>
<p><strong>Outcomes.</strong> The primary outcomes are monthly recorded-crime <strong>counts</strong> for thirteen categories and their total (“aggregate”). Latest-outcome positive shares were computed in the experiment. They are snapshot stocks with vintage-dependent follow-up, so they remain exploratory and are not interpreted here.</p>
<p><strong>Estimator.</strong> For each outcome separately, the MPS series and each donor series are standardised with their own pre-Drop 1 mean and standard deviation. Non-negative donor weights summing to one minimise the squared standardised pre-Drop 1 error. The synthetic path is</p>
<p><span class="math display">\[\hat y_t = \bar y_{\text{pre}} + s_{y,\text{pre}} \sum_j w_j \frac{x_{jt} - \bar x_{j,\text{pre}}}{s_{j,\text{pre}}}.\]</span></p>
<p>This is a convex combination of standardised donors mapped back to the MPS scale, not of donor levels. The gap is <span class="math inline">\(G_t = y_t - \hat y_t\)</span>.</p>
<p><strong>Estimands.</strong> A two-break segmented regression on the gap has a level and a slope term at December 2022 and at March 2024. It yields three distinct post-2024 quantities:</p>
<ol type="1">
<li>the incremental level change at March 2024, <span class="math inline">\(d_2\)</span>, relative to the extrapolated between-break line;</li>
<li>the descriptive mean post-March 2024 gap;</li>
<li>the <strong>post-March 2024 mean departure from the extrapolated pre-Drop 1 gap trend</strong>, the main persistent estimand. It is reported as a percentage of the MPS pre-Drop 1 monthly mean for the series.</li>
</ol>
<p>Temporary departures are measured separately. For each break, the gap in event months −3 to 11 is compared with a line fitted to event months −15 to −4, under three reference paths. The early, late and decay statistics are scaled by each unit’s own pre-Drop 1 fit error.</p>
</section>
<section id="two-comparison-pools" class="level2">
<h2 class="anchored" data-anchor-id="two-comparison-pools">4. Two comparison pools</h2>
<p><strong>Six-force baseline.</strong> The six forces are those of version 1: Avon and Somerset, Merseyside, Thames Valley, West Mercia, West Midlands and West Yorkshire. They are kept exactly as in version 1 so that results remain comparable. West Midlands would fail the national screen, because it had its own in-window CONNECT migration. In practice it carries no aggregate weight, and removing it leaves the six-force aggregate unchanged.</p>
<p><strong>Nationally screened pool.</strong> Every England and Wales territorial force was considered, subject to these rules, fixed before the national post-period estimates were run:</p>
<ul>
<li><strong>E1</strong>: territorial England and Wales force (excludes British Transport Police and PSNI).</li>
<li><strong>E2</strong>: no direct interference with the MPS (excludes the City of London Police).</li>
<li><strong>E3</strong>: a street file in every month from February 2019 to April 2026.</li>
<li><strong>E4</strong>: no month below half the median of the surrounding twelve months. This is a conservative low-count flag, not proof of a supply failure.</li>
<li><strong>E5</strong>: no documented change of crime-recording system inside the window.</li>
</ul>
<p>Forces where no such change was found are <em>not</em> certified clean. Evidence judged unclear is recorded, and sensitivity pools exclude those forces.</p>
<p>Of 42 England and Wales territorial alternatives to the MPS, <strong>30 are eligible</strong>. 14 archive units are excluded, as shown in Table 1.</p>
<p>The eligible forces have different levels of IT-change evidence: - 10 have specific but unclear evidence of an IT or recording change: Avon and Somerset Constabulary, Bedfordshire Police, Cambridgeshire Constabulary, Dorset Police, Hampshire Constabulary, Hertfordshire Constabulary, Merseyside Police, Sussex Police, Thames Valley Police, Warwickshire Police; - the other 20 have no in-window change located.</p>
<p><strong>Table 1.</strong> Units excluded from the national pool.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Excluded unit</th>
<th>Reason(s)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>British Transport Police</td>
<td>E1: non-territorial force; London rail network overlaps MPS area; files carry no Crime IDs; E3: 16 missing month(s) 2023-07..2026-04</td>
</tr>
<tr class="even">
<td>City of London Police</td>
<td>E2: enclave inside the MPS area; interference with the treated unit; E3: 1 missing month(s) 2022-06..2022-06; E4: extreme low-count flag in 2020-04, 2020-05, 2021-01, 2021-02</td>
</tr>
<tr class="odd">
<td>Cumbria Constabulary</td>
<td>E5: First phase of Mark43 RMS went live during financial year 2024/25; exact month unresolved</td>
</tr>
<tr class="even">
<td>Devon &amp; Cornwall Police</td>
<td>E3: 9 missing month(s) 2022-11..2023-07; E5: police.uk changelog: new records system from Nov 2022</td>
</tr>
<tr class="odd">
<td>Dyfed-Powys Police</td>
<td>E4: extreme low-count flag in 2023-05, 2024-01, 2024-02, 2024-03, 2024-04; E5: Niche RMS implemented May 2023; public accounts and inspection document transition</td>
</tr>
<tr class="even">
<td>Gloucestershire Constabulary</td>
<td>E3: 3 missing month(s) 2026-02..2026-04</td>
</tr>
<tr class="odd">
<td>Greater Manchester Police</td>
<td>E3: 81 missing month(s) 2019-07..2026-04; E5: police.uk changelog: change in IT systems, no crime data from Jul 2019</td>
</tr>
<tr class="even">
<td>Humberside Police</td>
<td>E5: police.uk changelog: “implementing a new crime recording system” (Known Issue shown Jul to Oct 2022)</td>
</tr>
<tr class="odd">
<td>Lincolnshire Police</td>
<td>E3: 1 missing month(s) 2023-04..2023-04</td>
</tr>
<tr class="even">
<td>Northumbria Police</td>
<td>E4: extreme low-count flag in 2026-01</td>
</tr>
<tr class="odd">
<td>Nottinghamshire Police</td>
<td>E3: 1 missing month(s) 2023-07..2023-07</td>
</tr>
<tr class="even">
<td>Police Service of Northern Ireland</td>
<td>E1: outside England and Wales</td>
</tr>
<tr class="odd">
<td>Staffordshire Police</td>
<td>E5: police.uk changelog: “change in IT systems”, May 2020 crime data partial, June 2020 onward not provided (refreshed Dec 2020)</td>
</tr>
<tr class="even">
<td>West Midlands Police</td>
<td>E5: police.uk changelog: “recent major system changes”, crime data not provided from April 2021 (supplied later)</td>
</tr>
</tbody>
</table>
<p><strong>Table 2.</strong> Pool composition for the aggregate series. The effective number of donors is 1/Σw².</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Pool</th>
<th>Donors</th>
<th>Positive aggregate weights</th>
<th>Effective donors</th>
<th>Largest aggregate weights</th>
<th>Pre-D1 fit RMSE, % of mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Six-force</td>
<td>6</td>
<td>3</td>
<td>2.0</td>
<td>Avon and Somerset Constabulary 0.65; West Yorkshire Police 0.26; West Mercia Police 0.10</td>
<td>4.6%</td>
</tr>
<tr class="even">
<td>National</td>
<td>30</td>
<td>7</td>
<td>3.8</td>
<td>Hertfordshire Constabulary 0.39; West Yorkshire Police 0.24; Cambridgeshire Constabulary 0.21</td>
<td>2.9%</td>
</tr>
</tbody>
</table>
<p>A larger candidate pool does not produce diffuse weights. In the national aggregate, the three forces with unclear IT-change evidence (Hertfordshire, Cambridgeshire, Bedfordshire) together carry <strong>0.63</strong> of the weight. Section 6 shows how much this matters.</p>
</section>
<section id="held-out-prediction-before-drop-1" class="level2">
<h2 class="anchored" data-anchor-id="held-out-prediction-before-drop-1">5. Held-out prediction before Drop 1</h2>
<p>The question is whether a pool predicts MPS recorded crime better <em>out of sample</em> before any CONNECT release. Every mean, scale and weight is refitted on training months only. Three schemes are used:</p>
<ul>
<li><strong>H1</strong> trains on February 2019 to November 2021 and predicts December 2021 to November 2022.</li>
<li><strong>H2</strong> uses six expanding origins, each predicting the next three months.</li>
<li><strong>H3</strong> repeats H1 without the pandemic months in training.</li>
</ul>
<p>The schemes overlap and are not independent replications. They also include the pre-go-live rise in autumn 2022, so anticipation cannot be excluded.</p>
<p><strong>Table 3.</strong> Held-out aggregate prediction error (RMSE, % of the MPS training mean).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Scheme</th>
<th>Six-force</th>
<th>National</th>
<th>National, equal weights</th>
<th>No donors (MPS training mean)</th>
<th>Categories improved (of 13)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>H1: last pre-D1 year</td>
<td>5.4%</td>
<td>3.2%</td>
<td>3.0%</td>
<td>8.2%</td>
<td>11</td>
</tr>
<tr class="even">
<td>H2: rolling 3-month</td>
<td>6.2%</td>
<td>4.1%</td>
<td>3.9%</td>
<td>7.2%</td>
<td>8</td>
</tr>
<tr class="odd">
<td>H3: H1 without pandemic training</td>
<td>5.8%</td>
<td>3.6%</td>
<td>3.4%</td>
<td>5.3%</td>
<td>8</td>
</tr>
</tbody>
</table>
<p>The national pool predicts the aggregate better in every scheme. Its advantage over six forces is not precisely estimated. Resampling paired three-month blocks of held-out errors gives these national-to-six RMSE ratios: - H1: 0.59 (range 0.27 to 1.07, from only 4 blocks); - H2: 0.66 (0.39 to 1.13).</p>
<p>Equal national weights do as well as optimised weights for the aggregate.</p>
<p>Improvement at category level is mixed: 11 of 13 categories in H1, but only 8 in H2. <strong>Shoplifting and theft from the person are worse with the national pool in all three schemes</strong>. In H1, theft from the person moves from 18.5% to 35.5%. The two categories with the strongest post-period signals therefore gain no predictive support from the wider pool.</p>
<p><strong>Robustness of the validation.</strong> The main eligibility rules use file availability and IT-change evidence up to April 2026. A pool screened on pre-Drop 1 information only (36 forces) gives similar aggregate errors: 3.2% (H1) and 3.5% (H2).</p>
<p>Random six-force pools drawn from the national pool separate pool size from composition. They match or beat the inherited six in 69% (H1) and 96% (H2) of draws, and match or beat the full national pool in 11.5% and 16%.</p>
<p>Treating each of the 30 pool forces in turn as the target, the rest of the pool beats the median random six-force pool for the aggregate in 80% (H1) and 87% (H2) of forces.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure-2.png" class="img-fluid figure-img"></p>
<figcaption>Analysis figure 2</figcaption>
</figure>
</div>
<p><strong>Figure 2.</strong> Held-out RMSE by series under each pool. The grey segment joins the two pools’ errors for a series. Lower is better; log scale.</p>
</section>
<section id="sustained-departures-after-march-2024" class="level2">
<h2 class="anchored" data-anchor-id="sustained-departures-after-march-2024">6. Sustained departures after March 2024</h2>
<section id="aggregate-recorded-crime" class="level3">
<h3 class="anchored" data-anchor-id="aggregate-recorded-crime">6.1 Aggregate recorded crime</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure-3.png" class="img-fluid figure-img"></p>
<figcaption>Analysis figure 3</figcaption>
</figure>
</div>
<p><strong>Figure 3.</strong> Aggregate recorded crime: MPS and the two synthetic comparisons (top) and the MPS-minus-synthetic gaps with their extrapolated pre-Drop 1 trends (bottom). Vertical lines: December 2022 and March 2024.</p>
<p><strong>Table 4.</strong> Aggregate persistent quantities under each pool. The MPS pre-Drop 1 mean is 67,785 crimes per month.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Aggregate</th>
<th>Six-force</th>
<th>National</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pre-Drop 1 fit RMSE, % of mean</td>
<td>4.6%</td>
<td>2.9%</td>
</tr>
<tr class="even">
<td>d1: level change at December 2022, %</td>
<td>+6.3%</td>
<td>+1.9%</td>
</tr>
<tr class="odd">
<td>d2: incremental level change at March 2024, %</td>
<td>−14.9%</td>
<td>−14.3%</td>
</tr>
<tr class="even">
<td>Descriptive mean post-March 2024 gap, crimes/month</td>
<td>−3,589</td>
<td>+5,473</td>
</tr>
<tr class="odd">
<td><strong>Post-March 2024 departure from pre-D1 trend, crimes/month</strong></td>
<td>+954</td>
<td>+5,505</td>
</tr>
<tr class="even">
<td><strong>Same, % of MPS pre-D1 mean</strong></td>
<td>+1.4%</td>
<td>+8.1%</td>
</tr>
<tr class="odd">
<td>Same, excluding first 6 months after each break, %</td>
<td>+3.3%</td>
<td>+9.3%</td>
</tr>
<tr class="even">
<td>Core robustness range, % (specifications, leave-one-out, timing)</td>
<td>−2.6 to 30.3</td>
<td>6.3 to 13.7</td>
</tr>
<tr class="odd">
<td>Placebo rank of scaled departure</td>
<td>5 of 7</td>
<td>10 of 31</td>
</tr>
</tbody>
</table>
<p>The two pools disagree on the aggregate: - <strong>Six forces:</strong> the departure from the pre-Drop 1 trend is near zero (+1.4%), but its sign flips within the robustness grid. The six-force fit is dominated by one donor. - <strong>National pool:</strong> the departure is positive (+8.1%) and stays positive in every run of the core grid (6.3 to 13.7%). It also stays positive in every screening sensitivity, which range from +7.7% to +15.2%. The largest value comes from dropping every force with unclear IT-change evidence (+15.2%). - <strong>Random donor compositions:</strong> random six-force subsets of the national pool span −0.4% to +21.2% (5th to 95th percentile), and random half-pools span +4.4% to +15.3%. - <strong>Trend dependence:</strong> the national descriptive mean gap (+5,473) is close to the trend-based departure. The national result is therefore not driven by the extrapolated pre-Drop 1 trend.</p>
<p>The sign of the national aggregate departure is robust; its size is not pinned down. The size is also not distinctive: scaled by each unit’s own pre-Drop 1 fit error, the MPS ranks 10th of 31 (Figure 5). Many untreated forces drift at least as far from their own synthetic comparisons over the same three years. This is a descriptive, model-conditional recorded-crime departure, not an estimate of a CONNECT effect.</p>
</section>
<section id="crime-categories" class="level3">
<h3 class="anchored" data-anchor-id="crime-categories">6.2 Crime categories</h3>
<p><strong>Table 5.</strong> Post-March 2024 departures from the pre-Drop 1 gap trend, as % of the MPS pre-Drop 1 mean for each series.</p>
<p>“Core range” covers alternative specifications, leave-one-positive-weight-donor-out fits and ±1-month timing shifts. It excludes the equal-weight estimator and the post-April 2026 extension. “Proportional mapping” holds the national weights fixed but maps donors to the MPS scale by their pre-D1 means instead of their standard deviations. It is a sensitivity with worse pre-fit, not a preferred estimator.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Series</th>
<th>Six-force departure %</th>
<th>National departure %</th>
<th>National core range %</th>
<th>Sign stable (national)</th>
<th>Placebo rank (national)</th>
<th>Placebo rank (six)</th>
<th>Proportional mapping % (national)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aggregate (13 categories)</td>
<td>+1.4%</td>
<td>+8.1%</td>
<td>6.3 to 13.7</td>
<td>yes</td>
<td>10 of 31</td>
<td>5 of 7</td>
<td>+8.6%</td>
</tr>
<tr class="even">
<td>Theft from the person</td>
<td>+127.3%</td>
<td>+106.2%</td>
<td>85.6 to 112.2</td>
<td>yes</td>
<td>1 of 31</td>
<td>1 of 7</td>
<td>+106.9%</td>
</tr>
<tr class="odd">
<td>Shoplifting</td>
<td>+67.6%</td>
<td>+79.4%</td>
<td>76.5 to 96.0</td>
<td>yes</td>
<td>1 of 31</td>
<td>1 of 7</td>
<td>+54.8%</td>
</tr>
<tr class="even">
<td>Public order</td>
<td>+7.2%</td>
<td>+15.4%</td>
<td>12.6 to 22.2</td>
<td>yes</td>
<td>8 of 31</td>
<td>7 of 7</td>
<td>+31.9%</td>
</tr>
<tr class="odd">
<td>Criminal damage and arson</td>
<td>+9.5%</td>
<td>+9.7%</td>
<td>8.5 to 13.2</td>
<td>yes</td>
<td>5 of 31</td>
<td>3 of 7</td>
<td>+15.3%</td>
</tr>
<tr class="even">
<td>Violence and sexual offences</td>
<td>+4.0%</td>
<td>+8.3%</td>
<td>5.7 to 17.8</td>
<td>yes</td>
<td>5 of 31</td>
<td>5 of 7</td>
<td>+12.2%</td>
</tr>
<tr class="odd">
<td>Other theft</td>
<td>−6.4%</td>
<td>+7.9%</td>
<td>−4.3 to 10.0</td>
<td>no</td>
<td>11 of 31</td>
<td>7 of 7</td>
<td>+3.3%</td>
</tr>
<tr class="even">
<td>Other crime</td>
<td>0.0%</td>
<td>+5.1%</td>
<td>0.7 to 9.7</td>
<td>yes</td>
<td>22 of 31</td>
<td>7 of 7</td>
<td>+3.8%</td>
</tr>
<tr class="odd">
<td>Burglary</td>
<td>+5.8%</td>
<td>+5.0%</td>
<td>0.3 to 15.7</td>
<td>yes</td>
<td>14 of 31</td>
<td>6 of 7</td>
<td>−6.4%</td>
</tr>
<tr class="even">
<td>Possession of weapons</td>
<td>+18.7%</td>
<td>+1.2%</td>
<td>−2.5 to 27.2</td>
<td>no</td>
<td>29 of 31</td>
<td>3 of 7</td>
<td>−15.0%</td>
</tr>
<tr class="odd">
<td>Drugs</td>
<td>−7.9%</td>
<td>−5.3%</td>
<td>−9.4 to 5.1</td>
<td>no</td>
<td>24 of 31</td>
<td>4 of 7</td>
<td>−11.3%</td>
</tr>
<tr class="even">
<td>Robbery</td>
<td>−15.3%</td>
<td>−6.1%</td>
<td>−18.5 to 6.3</td>
<td>no</td>
<td>23 of 31</td>
<td>4 of 7</td>
<td>−2.0%</td>
</tr>
<tr class="odd">
<td>Vehicle crime</td>
<td>−8.0%</td>
<td>−13.4%</td>
<td>−15.7 to −9.6</td>
<td>yes</td>
<td>4 of 31</td>
<td>4 of 7</td>
<td>−16.0%</td>
</tr>
<tr class="even">
<td>Bicycle theft</td>
<td>−9.3%</td>
<td>−19.3%</td>
<td>−26.6 to 31.6</td>
<td>no</td>
<td>14 of 31</td>
<td>6 of 7</td>
<td>−21.5%</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure-4.png" class="img-fluid figure-img"></p>
<figcaption>Analysis figure 4</figcaption>
</figure>
</div>
<p><strong>Figure 4.</strong> Post-March 2024 departures under each pool (dots) with their core robustness ranges (lines). Shoplifting and theft from the person are shown on their own scale.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure-5.png" class="img-fluid figure-img"></p>
<figcaption>Analysis figure 5</figcaption>
</figure>
</div>
<p><strong>Figure 5.</strong> Scaled post-March 2024 departures for the MPS (diamond) and for each of the 30 national-pool forces treated as if it were the MPS (grey; the MPS is never a donor). Only shoplifting and theft from the person place the MPS outside the placebo spread.</p>
<p><strong>Shoplifting and theft from the person.</strong> Both pools find large and persistent positive departures:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Shoplifting, six-force</th>
<th>Shoplifting, national</th>
<th>Theft from the person, six-force</th>
<th>Theft from the person, national</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Post-March 2024 departure</td>
<td>+67.6%</td>
<td>+79.4%</td>
<td>+127.3%</td>
<td>+106.2%</td>
</tr>
<tr class="even">
<td>Excluding the first six months after each break</td>
<td>+70.3%</td>
<td>+82.5%</td>
<td>+137.1%</td>
<td>+115.5%</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Distinctiveness.</strong> Each ranks first of 31 national units on both the scaled departure and its t-ratio, and first of 7 under six forces.</li>
<li><strong>Robustness.</strong> Each stays large in every screening pool and under the proportional mapping.</li>
<li><strong>Timing.</strong> The departures grow over time. Against the national comparison, shoplifting averages +22.3% between the breaks, then +76.0% and +82.3% in the two following years. Theft from the person averages +63.7%, then +125.5% and +89.6%.</li>
<li><strong>Caveats.</strong> Neither aligns cleanly with a single CONNECT date, the national pool predicts both <em>less</em> well before Drop 1, and a recording or classification explanation cannot be excluded.</li>
</ul>
<p><strong>Other categories.</strong> - <strong>Vehicle crime</strong> is negative in every run (−13.4% nationally), but ranks only 4th of 31. - <strong>Positive and stable nationally but not distinctive:</strong> criminal damage and arson, violence and sexual offences, public order, burglary. Their placebo ranks are 5, 5, 8, 14 of 31. - <strong>Burglary</strong> is particularly fragile. It changes sign under the proportional mapping, and one of its larger national donors (Surrey, weight 0.26) has an unexplained burglary break. - <strong>Sign not stable within the national robustness grid:</strong> drugs, other theft, bicycle theft, robbery and possession of weapons. These are not interpreted.</p>
</section>
</section>
<section id="temporary-departures-around-each-break" class="level2">
<h2 class="anchored" data-anchor-id="temporary-departures-around-each-break">7. Temporary departures around each break</h2>
<p>The persistent model cannot represent a disruption that fades. For each break, the MPS gap is compared with a local reference line fitted to event months −15 to −4, with the three lead months held out. Five summary statistics are computed:</p>
<ul>
<li>the lead months;</li>
<li>months 0 to 2;</li>
<li>months 3 to 5;</li>
<li>months 6 to 11;</li>
<li>a decay contrast (months 0 to 5 minus months 6 to 11).</li>
</ul>
<p>Each statistic is scaled by the unit’s own pre-Drop 1 fit error.</p>
<p>Calibration comes from the same statistics for every pool force at every feasible fake break month. Under the national pool that gives 30 forces × 31 dates. A statistic is <strong>flagged</strong> only if its placebo exceedance share is at most 0.05 under all three reference paths (local trend, local level, seasonally adjusted local trend). Placebo draws overlap in time and share forces, so exceedance shares are descriptive, not exact p-values.</p>
<p>Across all 168 count series × break × statistic combinations, the rule flags 8 national and 6 six-force results. The rule’s self-calibrated frequency implies about 2.3 and 1.6 flags by chance. These benchmarks are dependent, not familywise error rates.</p>
<ul>
<li><strong>National flags:</strong> Aggregate (13 categories) (Drop 1, decay contrast); Criminal damage and arson (Drop 1, decay contrast); Other crime (March 2024, decay contrast); Other crime (March 2024, months 0-2); Other theft (March 2024, months 0-2); Shoplifting (March 2024, months 0-5); Shoplifting (March 2024, months 3-5); Violence and sexual offences (Drop 1, decay contrast).</li>
<li><strong>Six-force flags:</strong> Criminal damage and arson (Drop 1, decay contrast); Drugs (March 2024, decay contrast); Other crime (March 2024, decay contrast); Other crime (March 2024, months 0-2); Public order (Drop 1, decay contrast); Shoplifting (March 2024, months 3-5).</li>
</ul>
<p>What the flags mean:</p>
<ul>
<li><strong>“Other crime”, March 2024.</strong>
<ul>
<li>The local-trend departure is −23.2% in months 0 to 2, returning to −1.2% in months 6 to 11.</li>
<li>Early bin: worst-reference exceedance 0.034.</li>
<li>Decay contrast: 0.049 nationally, against 0.0053 under six forces.</li>
</ul>
This is the clearest candidate temporary pattern, with a much smaller margin under the wider calibration.</li>
<li><strong>Other theft, March 2024.</strong>
<ul>
<li>The first three months fall (−27.8%; flagged nationally).</li>
<li>The later bins stay negative (−22.0% in months 6 to 11).</li>
</ul>
This is an early drop without a demonstrated recovery.</li>
<li><strong>Drugs, March 2024.</strong> The decay contrast is still negative (−27.6%), but its worst-reference exceedance rises from 0.032 (six) to 0.063 (national), and it loses the flag. Version 1’s drugs finding is therefore weaker. The drugs decline had also begun before March 2024.</li>
<li><strong>Aggregate, March 2024.</strong> The local-trend departure is −20.2% in the first half-year, but its worst-reference exceedance is 0.38. No distinctive temporary aggregate fall is established.</li>
<li><strong>Drop 1.</strong> No early post-break bin is flagged in either pool. The national Drop 1 decay flags (aggregate, criminal damage, violence and sexual offences) reflect departures that <em>grow</em> later. For example, the aggregate moves from +5.6% in months 0 to 5 to +17.6% in months 6 to 11. That is not a dip and recovery.</li>
<li><strong>Shoplifting, March 2024.</strong> The flags accompany a sustained rise, not a temporary disruption.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure-6.png" class="img-fluid figure-img"></p>
<figcaption>Analysis figure 6</figcaption>
</figure>
</div>
<p><strong>Figure 6.</strong> Event-time departures from the local pre-break trend around March 2024, national pool, scaled by pre-Drop 1 fit error. Grey bands: pointwise placebo ranges from national-pool forces at all feasible fake break dates. These are not confidence bands.</p>
</section>
<section id="uncertainty-what-the-intervals-do-and-do-not-mean" class="level2">
<h2 class="anchored" data-anchor-id="uncertainty-what-the-intervals-do-and-do-not-mean">8. Uncertainty: what the intervals do and do not mean</h2>
<p>Version 1 reported Newey-West (HAC) standard errors, conditional on the estimated weights and the linear segment model, and warned that an in-time placebo made them look optimistic. The final review tested this directly. Every comparison force was treated in turn as if it were the MPS, using the remainder of its pool as donors (the MPS is never a donor). None of these forces experienced the MPS’s CONNECT releases, so if the interval were calibrated and the forces had no changes of their own, a 95% interval would exclude zero about 5% of the time.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Six-force</th>
<th>National</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Placebo force-series analysed</td>
<td>84</td>
<td>420</td>
</tr>
<tr class="even">
<td>Nominal 95% HAC interval excludes zero, all series</td>
<td>56%</td>
<td>47%</td>
</tr>
<tr class="odd">
<td>Same, aggregate</td>
<td>67%</td>
<td>50%</td>
</tr>
<tr class="even">
<td>95th percentile of placebo |t|, aggregate</td>
<td>17.2</td>
<td>7.9</td>
</tr>
<tr class="odd">
<td>MPS aggregate t (rank of |t|)</td>
<td>0.40 (5 of 7)</td>
<td>3.29 (11 of 31)</td>
</tr>
<tr class="even">
<td>June 2022 in-time placebo: coefficients with nominal p &lt; 0.05</td>
<td>6 of 28</td>
<td>7 of 28</td>
</tr>
</tbody>
</table>
<p>Some placebo forces will have genuine changes of their own, so these shares overstate miscalibration to an unknown degree. Even so, they are roughly ten times the nominal rate. Over a three-year horizon, the main source of variation in an extrapolated departure is drift between a force and its synthetic comparison, which HAC standard errors do not capture.</p>
<p>This paper therefore does not use HAC p-values or intervals as evidence. The comparative statements rest on: - placebo ranks among units analysed identically; - sign stability across specifications, donor deletions and timing shifts; - resampling of donor composition.</p>
<p>None of these is a sampling-based confidence interval. With 31 units, a rank of 1 corresponds to a placebo share of 1/31 ≈ 0.032.</p>
<p><strong>Computation checks.</strong> - All 252 primary and held-out weight fits were certified optimal by a solver-independent duality-gap bound (largest relative gap 3.8e-06). An independent solver agrees to 6e-07 in every weight. - Corrupting held-out and post-period data changed no training weight (238 checks). - This notebook recomputes the primary estimates from the compact panel (Appendix A).</p>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">9. Discussion</h2>
<p><strong>What the wider comparison changes.</strong></p>
<ul>
<li><strong>Validation.</strong> Prediction of aggregate recorded crime before CONNECT improves, which supports using the national pool at least as a robustness comparison. The improvement is imprecise, and it does not extend to the categories with the strongest post-period signals.</li>
<li><strong>Aggregate reading.</strong> It changes the aggregate from “no departure” (six forces, driven by one dominant donor) to “a positive departure of uncertain size”. The size depends on screening choices, and forces with unclear IT-change evidence carry most of the weight.</li>
<li><strong>Distinctiveness.</strong> Against untreated forces analysed the same way, neither pool’s aggregate departure is unusual. The defensible statement is that <strong>there is no evidence of an MPS-specific shift in total recorded crime</strong> relative to comparable forces, not that there is none, and not that there is a positive one.</li>
<li><strong>Temporary patterns.</strong> It weakens version 1’s drugs result and leaves a brief, narrowly supported fall in “other crime” around the March 2024 recording switch.</li>
</ul>
<p><strong>What it does not change.</strong></p>
<ul>
<li><strong>Persistent categories.</strong> Shoplifting and theft from the person diverge from every comparison far more than any placebo force diverges from its own, under every pool, specification and mapping examined. This is the most stable descriptive finding across both versions.</li>
<li><strong>Why these categories diverged.</strong> It remains unexplained. The rises build between the breaks and continue afterwards, so they do not isolate either CONNECT date. Theft from the person was already above its projection after Drop 1 and stepped up again in autumn 2023, months before the March 2024 switch. Offsetting movements in other theft, and a change of recording system, make a classification explanation plausible. Genuine London-specific trends in these offences cannot be ruled out either.</li>
</ul>
<p><strong>Identification.</strong> A causal reading would need the MPS gap to have stayed on its pre-period path without CONNECT. That assumption is weakened by:</p>
<ul>
<li>the pandemic within the pre-period;</li>
<li>the pre-go-live movement in autumn 2022;</li>
<li>the coincidence of Drop 2 with a documented recording-system change and late data supply;</li>
<li>the unexplained May 2026 criminal-damage break.</li>
</ul>
<p>None of these is removed by a larger donor pool.</p>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">10. Limitations</h2>
<ol type="1">
<li><strong>Not causal.</strong> The results are model-conditional associations in recorded crime. Recorded crime mixes offending, reporting, police activity, recording practice, geocoding and publication, and the design cannot separate them.</li>
<li><strong>Joint second break.</strong> Drop 2 and the CRIS-to-CONNECT recording cutover are not separately identified. Drop 1 and the second break are only 15 months apart.</li>
<li><strong>Donor screening is retrospective and incomplete.</strong> The rules use file availability and IT-change evidence up to April 2026, and were finalised during the experiment, not preregistered. All 30 eligible forces have unresolved audit risk. The 10 forces with unclear evidence carry 0.63 of the aggregate weight. Non-system recording-practice changes were not systematically audited; Gwent’s Crime Data Integrity Team, introduced 1 July 2023, is one documented example. Some pool forces have unexplained category-level breaks, notably Gwent criminal damage and Surrey burglary.</li>
<li><strong>Vintages.</strong> Three archive vintages are spliced. Overlapping snapshots show force-month revisions of up to 39.6% (Staffordshire Police), and revision size differs by force. The July 2023 / July 2026 seam cannot be audited by overlap.</li>
<li><strong>Estimator.</strong> Donors are mapped to the MPS scale by pre-Drop 1 standard deviations, which the 2020 pandemic trough dominates. Category results other than shoplifting and theft from the person are sensitive to this choice. The persistent estimand extrapolates a linear pandemic-era gap trend for up to three and a half years.</li>
<li><strong>Inference.</strong> No calibrated sampling interval is available for the persistent departures. HAC intervals fail the placebo calibration. Placebo ranks come from non-randomly assigned units that may have their own changes. The specification search across pools, categories, breaks and temporary-effect statistics is not fully corrected for multiplicity.</li>
<li><strong>Validation.</strong> Held-out validation is short, overlapping and pandemic-affected. It shows better aggregate prediction, not a valid post-period counterfactual.</li>
<li><strong>Endpoint.</strong> The analysis ends in April 2026 because of the unexplained MPS criminal-damage collapse from May 2026. The July 2026 endpoint appears only as a sensitivity; it needs 29 national donors because one force lacks a July file. A May 2026 change affecting other MPS categories less visibly cannot be excluded.</li>
<li><strong>Outcome shares.</strong> Latest-outcome positive shares are exploratory snapshot stocks and are not interpreted.</li>
</ol>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">11. Conclusion</h2>
<p>With a standardised synthetic control fitted before Drop 1, the two comparison pools agree that MPS recorded <strong>shoplifting</strong> and <strong>theft from the person</strong> departed far from their pre-CONNECT trajectories after 2023: by about 79% and 106% of their pre-Drop 1 levels after March 2024 in the national comparison. Both departures are more extreme than any untreated force’s, but their timing does not isolate either CONNECT release, and a recording explanation remains plausible.</p>
<p>For <strong>total recorded crime</strong>, the six-force comparison shows essentially no departure and the national comparison a positive one (+8.1%). Untreated forces show departures of similar size, so neither amounts to evidence of an MPS-specific change.</p>
<p>Around the March 2024 recording transition there is a brief, narrowly supported fall in “other crime”, and an early fall in other theft without demonstrated recovery. After Drop 1 there is no distinctive short-run departure.</p>
<p>These are descriptive, model-conditional findings about recorded crime. They do not show that CONNECT caused changes in crime or in its recording.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p><strong>Institutional and data sources</strong> (see <a href="https://github.com/AndreasThinks/impact-of-connect-drop/blob/f52b08ae3470f1986f663165d2f97fa3c605b596/papers/connect_two_drops/sources.md"><code>../sources.md</code></a> for retrieval notes; eligibility sources were re-checked on 29 September 2026 where retrievable).</p>
<ul>
<li>Metropolitan Police Service (2023). <em>CONNECT Update</em>. Report to the MOPAC Finance, Change and People Oversight Board, 30 June 2023. https://www.london.gov.uk/sites/default/files/2023-12/Item%202%20MPS%20CONNECT%20Update%20June%202023.pdf</li>
<li>MOPAC (2023). <em>DMPC Decision PCD 1507: CONNECT Drop 2 Training Approach</em>, signed 4 August 2023. https://www.london.gov.uk/media/104841/download</li>
<li>MOPAC (2023). <em>DMPC Decision PCD1572: CONNECT Full Business Case, 3rd iteration</em>, signed 21 December 2023. https://www.london.gov.uk/media/104996/download</li>
<li>Metropolitan Police Service (2025). FOI 01.FOI.25.042468, <em>Crime statistics data extracted for FOI requests</em>. https://www.met.police.uk/foi-ai/metropolitan-police/disclosure-2025/january-2025/crime-statistics-data-extracted-foi-requests/</li>
<li>Metropolitan Police Service (2024). FOI 01.FOI.24.036412, <em>Software for recording crime</em>. https://www.met.police.uk/foi-ai/metropolitan-police/disclosure-2024/june-2024/software-recording-crime/</li>
<li>data.police.uk. Data archive and changelog. https://data.police.uk/data/archive ; https://data.police.uk/changelog/ (changelog re-checked 29 September 2026)</li>
<li>Greater London Authority, London Datastore. <em>MPS Monthly Crime Dashboard Data</em>. https://data.london.gov.uk/dataset/mps-monthly-crime-dashboard-data-e5n6w</li>
<li>Independent Office for Police Conduct (2021). <em>Recommendation: West Midlands Police, April 2021</em> (response published 5 July 2021). https://www.policeconduct.gov.uk/our-work/learning/recommendation-west-midlands-police-april-2021</li>
<li>HM Inspectorate of Constabulary and Fire &amp; Rescue Services. <em>PEEL 2023-25: Dyfed-Powys Police</em>. https://s3-eu-west-2.amazonaws.com/assets-hmicfrs.justiceinspectorates.gov.uk/uploads/peel-assessment-2023-25-dyfed-powys.pdf</li>
<li>Cumbria Constabulary. <em>Chief Constable summary statement of accounts 2024/25</em> (Mark43 first phase; returned HTTP 403 on re-check). https://www.cumbria.police.uk/SysSiteAssets/media/images/cumbria/about-us/stat-accs-20242025-new/the-chief-constable-summary-statement-of-accounts-2024-25.pdf</li>
<li>Northumbria PCC (2025). <em>Response to HMICFRS PEEL spotlight on crime recording</em>. https://northumbria-pcc.gov.uk/v3/wp-content/uploads/2025/10/PEEL-Spotlight-How-effectively-do-the-police-record-crime-Section-55-Northumbria-PCC-Response.pdf</li>
<li>Gwent PCC (2025). <em>Annual report on data quality in relation to crime and incidents</em>. https://www.gwent.pcc.police.uk/media/0qbj5ip4/4c-annual-report-on-data-quality-in-relation-to-crime-and-incidents-2025.pdf</li>
<li>Varotsis, A. (2024). The Impact of CONNECT Drop 1 on Crime Rates and Detection in the Metropolitan Police: Synthetic Control Analysis. <em>CrimRxiv</em>. https://doi.org/10.21428/cb6ab371.d08ca57c</li>
</ul>
<p><strong>Methods</strong> (DOIs as checked for version 1).</p>
<ul>
<li>Abadie, A., Diamond, A. and Hainmueller, J. (2010). Synthetic control methods for comparative case studies. <em>Journal of the American Statistical Association</em> 105(490), 493-505. https://doi.org/10.1198/jasa.2009.ap08746</li>
<li>Abadie, A. (2021). Using synthetic controls: feasibility, data requirements, and methodological aspects. <em>Journal of Economic Literature</em> 59(2), 391-425. https://doi.org/10.1257/jel.20191450</li>
<li>Box, G. E. P. and Tiao, G. C. (1975). Intervention analysis with applications to economic and environmental problems. <em>Journal of the American Statistical Association</em> 70(349), 70-79. https://doi.org/10.1080/01621459.1975.10480264</li>
<li>Doudchenko, N. and Imbens, G. W. (2016). Balancing, regression, difference-in-differences and synthetic control methods: a synthesis. NBER Working Paper 22791. https://doi.org/10.3386/w22791</li>
<li>Ferman, B. and Pinto, C. (2021). Synthetic controls with imperfect pretreatment fit. <em>Quantitative Economics</em> 12(4), 1197-1221. https://doi.org/10.3982/QE1596</li>
<li>Frank, M. and Wolfe, P. (1956). An algorithm for quadratic programming. <em>Naval Research Logistics Quarterly</em> 3(1-2), 95-110. https://doi.org/10.1002/nav.3800030109</li>
<li>Linden, A. (2015). Conducting interrupted time-series analysis for single- and multiple-group comparisons. <em>The Stata Journal</em> 15(2), 480-500. https://doi.org/10.1177/1536867X1501500208</li>
<li>Lopez Bernal, J., Cummins, S. and Gasparrini, A. (2017). Interrupted time series regression for the evaluation of public health interventions: a tutorial. <em>International Journal of Epidemiology</em> 46(1), 348-355. https://doi.org/10.1093/ije/dyw098</li>
<li>Newey, W. K. and West, K. D. (1987). A simple, positive semi-definite, heteroskedasticity and autocorrelation consistent covariance matrix. <em>Econometrica</em> 55(3), 703-708. https://doi.org/10.2307/1913610</li>
<li>Wagner, A. K., Soumerai, S. B., Zhang, F. and Ross-Degnan, D. (2002). Segmented regression analysis of interrupted time series studies in medication use research. <em>Journal of Clinical Pharmacy and Therapeutics</em> 27(4), 299-309. https://doi.org/10.1046/j.1365-2710.2002.00430.x</li>
</ul>
</section>
<section id="appendix-a.-reproducibility" class="level2">
<h2 class="anchored" data-anchor-id="appendix-a.-reproducibility">Appendix A. Reproducibility</h2>
<p>The notebook runs from <code>papers/connect_two_drops/v2/</code> using only <code>data/</code>, <code>src/</code> and the unchanged version 1 estimator in <code>../src/</code>. It needs no raw police.uk ZIPs, no Git LFS and no absolute paths. From the repository root:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> sync <span class="at">--locked</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run pytest <span class="at">-q</span> papers/connect_two_drops/v2/tests</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run jupyter nbconvert <span class="at">--to</span> notebook <span class="at">--execute</span> <span class="at">--inplace</span> papers/connect_two_drops/v2/paper_v2.ipynb</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="ex">quarto</span> render papers/connect_two_drops/v2/paper_v2.ipynb <span class="at">--to</span> html</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>build_inputs.py</code> regenerates <code>data/</code> from the executed national-pool experiment, recording source and output SHA-256 values in <code>data/MANIFEST.json</code>. <code>build_notebook.py</code> regenerates this notebook’s cells. Neither is needed to execute the paper.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Check</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Primary estimates recomputed from <code>data/panel_counts.csv</code></td>
<td>max</td>
</tr>
<tr class="even">
<td>National aggregate placebo rank recomputed</td>
<td>10 of 31</td>
</tr>
<tr class="odd">
<td>Active-set fallback fits in this recomputation</td>
<td>2</td>
</tr>
<tr class="even">
<td>Recomputation time</td>
<td>8 s</td>
</tr>
<tr class="odd">
<td>v1 estimator SHA-256</td>
<td>6023451cf688dd6a18b1810673a0b56bda74d1d3562e5f517bca3697f425fdc6</td>
</tr>
<tr class="even">
<td>Panel SHA-256</td>
<td>d840abbbf2faac991747bf53b3c061275daa884647fdcf75ee5cb83d70e2c9a1</td>
</tr>
<tr class="odd">
<td>Experiment baseline-module SHA-256</td>
<td>6023451cf688dd6a18b1810673a0b56bda74d1d3562e5f517bca3697f425fdc6</td>
</tr>
<tr class="even">
<td>Experiment seeds</td>
<td>heldout_random6 20260928, post_random6 20260929, post_random_half 20260930, cross_unit 20260928</td>
</tr>
<tr class="odd">
<td>Python / numpy / pandas / scipy / statsmodels / matplotlib</td>
<td>3.12.3 / 2.2.0 / 2.2.3 / 1.14.1 / 0.14.4 / 3.10.0</td>
</tr>
</tbody>
</table>
</section>
<section id="appendix-b.-changes-from-version-1" class="level2">
<h2 class="anchored" data-anchor-id="appendix-b.-changes-from-version-1">Appendix B. Changes from version 1</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Area</th>
<th>Version 1</th>
<th>Version 2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Comparison</td>
<td>Six forces</td>
<td>Six forces and a national pool of 30 screened forces, reported side by side</td>
</tr>
<tr class="even">
<td>Validation</td>
<td>None out of sample</td>
<td>Held-out pre-Drop 1 prediction (three schemes), random-pool and cross-force validation</td>
</tr>
<tr class="odd">
<td>Placebo units</td>
<td>7</td>
<td>7 and 31</td>
</tr>
<tr class="even">
<td>Interval evidence</td>
<td>HAC p-values, described as optimistic</td>
<td>HAC intervals shown to fail placebo calibration; not used as evidence</td>
</tr>
<tr class="odd">
<td>Aggregate conclusion</td>
<td>Near-zero departure; sign depends on one donor</td>
<td>Pool-dependent; positive nationally but not distinctive (rank 10 of 31)</td>
</tr>
<tr class="even">
<td>Shoplifting, theft from the person</td>
<td>Persistent, extreme against placebos</td>
<td>Unchanged in substance under both pools; stable under an alternative scale mapping</td>
</tr>
<tr class="odd">
<td>Temporary patterns</td>
<td>Drugs and “other crime”</td>
<td>“Other crime” retained with narrow margin; drugs weakened; other theft early fall</td>
</tr>
<tr class="even">
<td>Sensitivities added</td>
<td></td>
<td>IT-change screening pools, random donor compositions, scale mapping, core robustness ranges</td>
</tr>
<tr class="odd">
<td>Unchanged</td>
<td></td>
<td>Estimator, break coding, April 2026 endpoint, temporary-effect definitions, counts as primary outcome</td>
</tr>
</tbody>
</table>
<p>Version 1 remains the record of the six-force analysis. Its numbers are reproduced here, not revised. The only substantive change to a version 1 statement is the interpretation of interval estimates (Section 8), which applies equally to both pools.</p>
</section>
<section id="appendix-c.-narrative-consistency-checks" class="level2">
<h2 class="anchored" data-anchor-id="appendix-c.-narrative-consistency-checks">Appendix C. Narrative consistency checks</h2>
<p>The discussion, conclusion and lay summary contain qualitative statements. The cell below asserts them against the frozen results, so the notebook fails instead of silently disagreeing if the inputs change.</p>
<pre class="text"><code>All narrative consistency checks passed.</code></pre>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script>
  const themeStorageKey = "theme-preference";
  const themeButtonClass = "theme-toggle-button";

  const root = document.documentElement;

  const getStoredTheme = () => {
    const stored = localStorage.getItem(themeStorageKey);
    return stored === "light" || stored === "dark" ? stored : null;
  };

  const getSystemTheme = () =>
    window.matchMedia("(prefers-color-scheme: light)").matches
      ? "light"
      : "dark";

  const setBootstrapTheme = (theme) => {
    document.querySelectorAll("[data-bs-theme]").forEach((element) => {
      element.setAttribute("data-bs-theme", theme);
    });
  };

  const updateButtonLabel = (theme) => {
    const button = document.querySelector(`.${themeButtonClass}`);
    if (!button) {
      return;
    }
    const nextThemeLabel =
      theme === "light" ? "Switch to dark mode" : "Switch to light mode";
    button.setAttribute("aria-label", nextThemeLabel);
    button.setAttribute("title", nextThemeLabel);
    button.setAttribute("aria-pressed", theme === "light");
    button.dataset.theme = theme;
  };

  const applyTheme = (theme, source) => {
    root.setAttribute("data-theme", theme);
    root.setAttribute("data-theme-source", source);
    setBootstrapTheme(theme);
    updateButtonLabel(theme);
  };

  const toggleTheme = () => {
    const currentTheme = root.getAttribute("data-theme") || getSystemTheme();
    const nextTheme = currentTheme === "light" ? "dark" : "light";
    localStorage.setItem(themeStorageKey, nextTheme);
    applyTheme(nextTheme, "user");
  };

  const createToggleButton = () => {
    if (document.querySelector(`.${themeButtonClass}`)) {
      return;
    }
    const container =
      document.querySelector(".quarto-navbar-tools") ||
      document.querySelector(".navbar .navbar-nav.ms-auto");
    if (!container) {
      return;
    }

    const button = document.createElement("button");
    button.type = "button";
    button.className = themeButtonClass;
    button.innerHTML = '<span aria-hidden="true">◐</span>';
    button.addEventListener("click", (event) => {
      event.preventDefault();
      toggleTheme();
    });

    container.appendChild(button);
  };

  const initTheme = () => {
    const storedTheme = getStoredTheme();
    if (storedTheme) {
      applyTheme(storedTheme, "user");
      return;
    }
    applyTheme(getSystemTheme(), "system");
  };

  const onReady = () => {
    createToggleButton();
    initTheme();
  };

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", onReady);
  } else {
    onReady();
  }

  const mediaQuery = window.matchMedia("(prefers-color-scheme: light)");
  mediaQuery.addEventListener("change", (event) => {
    if (getStoredTheme()) {
      return;
    }
    applyTheme(event.matches ? "light" : "dark", "system");
  });
</script>
<script>
  // Reading progress bar: only on pages with a title block (posts, papers,
  // slides summaries) that are long enough to be worth tracking.
  (() => {
    const init = () => {
      if (!document.getElementById("title-block-header")) {
        return;
      }
      const doc = document.documentElement;
      if (doc.scrollHeight < doc.clientHeight * 1.5) {
        return;
      }
      const bar = document.createElement("div");
      bar.className = "reading-progress";
      bar.setAttribute("aria-hidden", "true");
      document.body.appendChild(bar);
      const update = () => {
        const max = doc.scrollHeight - doc.clientHeight;
        const progress = max > 0 ? Math.min(doc.scrollTop / max, 1) : 0;
        bar.style.transform = `scaleX(${progress})`;
      };
      document.addEventListener("scroll", update, { passive: true });
      window.addEventListener("resize", update);
      update();
    };
    if (document.readyState === "loading") {
      document.addEventListener("DOMContentLoaded", init);
    } else {
      init();
    }
  })();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/andreasthinks\.me");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Andreas Varotsis</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://quarto.org">
<p>made with quarto</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://fosstodon.org/@AndreasThinks">
      <i class="bi bi-mastodon" role="img" aria-label="Mastodon">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/AndreasThinks">
      <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/avarotsis/">
      <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="mailto:andreas.varotsis@gmail.com">
      <i class="bi bi-envelope" role="img" aria-label="Email">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml">
      <i class="bi bi-rss" role="img" aria-label="RSS feed">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>